### ISSUE TITLE
Failing tests and segfaults with Intel compiler

### ISSUE THREAD

**Issue by bennybp** [wjakob/pybind11#94]
I fixed a few minor issues when compiling pybind11 with the Intel compiler (v15). After fixing, there are two failing tests.

In example5, Intel seems to use an additional move construction of the lambda payload test at the end. This is interesting, but probably harmless.

    Payload constructor
    Payload copy constructor
    Payload move constructor
    Payload move constructor
    Payload destructor
    Payload destructor
    Payload destructor
    Payload destructor

example8, however, segfaults around cast.h:451 or shortly thereafter. It could be a bug or an an idiosyncrasy  somewhere in the Intel compiler, since gcc seems to be fine.

I'll see if I can track it down in the next few days but if anyone wants to chime in feel free.

PS: The one fix I had to do to get it to compile under Intel was to change the signature of `ignore_unused` in attr.h. Intel rejects this for some reason...

    -template<class T> void ignore_unused(const T&) { }
    +template<class T> void ignore_unused(const T []) { }

**Comment by wjakob** [comment]
Can you provide the error message for the original ignore_unused? The latter version may compile on Intel but doesn't look right to me (why an array?!)-- perhaps there is another workaround that makes all compilers happy.

**Comment by wjakob** [comment]
for reference, what OS is this?

**Comment by bennybp** [comment]
I thought that was weird also. Here's the error:

    <path>/include/pybind11/attr.h(268): error: argument of type "int *" is incompatible with parameter of type "const int (&)[2]"
            ignore_unused(unused);

I'm willing to bet that is actually a bug in Intel - I'll see what they say. It only seems to happen when expanding the parameter pack like that.

I can't believe it's this hard to ignore a variable! I don't really have any other portable workaround. I have seen something like 

    static void init(const Args&... args, function_record *r) {
        using ignore = int[];
        ignore{ 0, (process_attribute<typename std::decay<Args>::type>::init(args, r), 0) ... };
    }

It seems to work on GCC 4.9.2 and Intel 15, but clang still reports an unused variable. I have never used that setup before, so I have no idea about its portability.

My OS in Fedora Linux.

**Comment by wjakob** [comment]
Yes, sounds like an Intel compiler bug. I'm actually surprised it can compile this codebase with minor modifications ;)

**Comment by bennybp** [comment]
Ok minor update. I finally installed Intel 2016, and the compilation issue with ignore_unused seems to be fixed.

The segfault is still there, though. It seems like once it gets into the depths of pybind11, information is lost about the derived type (vtable is empty/corrupted for a pointer). I wish I could get a small working example outside of pybind11, but I can't seem to trigger it.

**Comment by wjakob** [comment]
Do you have a backtrace of what is segfaulting? Does it happen with the included example?

**Comment by bennybp** [comment]
Yes and yes. It happens with example8.

    #0  0x000000000000000a in ?? ()
    #1  0x00007ffff003b4ae in print_object_3 (obj=...) at /home/ben/pybind11/example/example8.cpp:90
    #2  0x00007ffff0052e60 in pybind11::detail::type_caster<std::tuple<ref<Object> const&>, void>::call<void, void (*)(ref<Object> const&), 0ul>(void (*&&)(ref<Object> const&), pybind11::detail::index_sequence<0ul>) (this=0x7fffffffc450, f=@0x7fffffffc488: 0x7ffff003b44f <print_object_3(ref<Object> const&)>) at /home/ben/pybind11/include/pybind11/cast.h:451
    #3  0x00007ffff0052e24 in pybind11::detail::type_caster<std::tuple<ref<Object> const&>, void>::call<void, void (*)(ref<Object> const&)>(void (*&&)(ref<Object> const&)) (this=0x7fffffffc450, f=@0x7fffffffc488: 0x7ffff003b44f <print_object_3(ref<Object> const&)>) at /home/ben/pybind11/include/pybind11/cast.h:441
    #4  0x00007ffff003e51b in pybind11::cpp_function::cpp_function<void, ref<Object> const&, pybind11::name, pybind11::sibling, pybind11::scope>(void (*)(ref<Object> const&), pybind11::name const&, pybind11::sibling const&, pybind11::scope const&)::{lambda(pybind11::detail::function_record*, pybind11::handle, pybind11::handle)#1}::operator()(pybind11::detail::function_record*, pybind11::handle, pybind11::handle) const (this=0x0, rec=0x55555584c380, pyArgs=..., parent=...) at /home/ben/pybind11/include/pybind11/pybind11.h:67
    #5  0x00007ffff003e5e3 in pybind11::cpp_function::cpp_function<void, ref<Object> const&, pybind11::name, pybind11::sibling, pybind11::scope>(void (*)(ref<Object> const&), pybind11::name const&, pybind11::sibling const&, pybind11::scope const&)::{lambda(pybind11::detail::function_record*, pybind11::handle, pybind11::handle)#1}::_FUN(pybind11::detail::function_record*, pybind11::handle, pybind11::handle) () at /home/ben/pybind11/include/pybind11/pybind11.h:55
    #6  0x00007fffeffc10de in pybind11::cpp_function::dispatcher (self=0x7ffff7e478a0, args=0x7ffff7e3e0b8, kwargs=0x0) at /home/ben/pybind11/include/pybind11/pybind11.h:404
    #7  0x00007ffff7a65651 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0


Inside the print_object_3:

    (gdb) info vtbl obj.m_ptr
    vtable for 'Object' @ 0x55555584af48 (subobject @ 0x55555584a790):
    [0]: 0xa
    [1]: 0x7ffff7d86320 <PyType_Type>

which is not correct. Passing by pointer instead (like print_object_4) works, though...

**Comment by wjakob** [comment]
My guess is that the actual problem might not be in how the function call to ``print_object_3`` is handled, but the creation of the object itself.

Stripping down the problematic lines a bit, we have 
```
for o in [make_object_1(), make_object_2(), MyObject1(3)]:
    print_object_3(o)
```

Does this still crash? If so, it would be interesting to check the items of the list individually.

**Comment by bennybp** [comment]
Found it :)

It actually happens when `print_object_3` is called, not when the object is created. In cast.h:451

    return f((Tuple) std::get<Index>(value)...);

For this type, this casts a `type_caster_holder<Object, ref<Object> >` to a `ref<Object> &` via the
user-defined conversion operator. This operator isn't being found by the Intel compiler. Instead, the C-style cast just reinterprets the type_caster_holder.

If you change the C-style cast to a static_cast, it will fail to compile. For some reason, if you remove the `explicit` from that particular conversion operator, it works.

My post on the Intel forums: https://software.intel.com/en-us/forums/intel-c-compiler/topic/610378

**Comment by wjakob** [comment]
awesome detective work! :) -- as a temporary workaround, we could make the type_caster_holder casting operating operator non-explicit when the intel compiler is detected.  Does it pass all testcases in this case? (except for the extra move constructor, which is minor and does not count as a failure as you mentioned)

What do you think?

**Comment by bennybp** [comment]
Yes, example 8 then passes. Only the `explicit operator T&()` should be changed, though, or else
the casting is ambiguous (for all compilers I've tested).

Do you oppose changing the `ignore_unused` function to the following? This should help with Intel 2015, and should be better than my first attempt

    inline void ignore_unused(int *) { }

I'm preparing a pull request with these changes, plus some other minor additions for the intel compiler (mostly options in the cmake file and warning supression).

**Comment by wjakob** [comment]
Changing ``ignore_unused`` as you proposed looks fine to me.

**Comment by wjakob** [comment]
Thank you again for the great detective work in tracking this down. Can this ticket be closed now, or is there a remaining issue?

Longer term it would be nice to have continuous integration support for ICC, but it looks like that is not yet possible (https://github.com/travis-ci/travis-ci/issues/4604).

**Comment by bennybp** [comment]
I think it can be closed. The remaining issue is with example 5 which isn't as big a deal, although it would be nice to have all tests pass. (I think the issue is that the compiler is missing an RVO opportunity).

Keep up the good work

**Comment by wjakob** [comment]
In the script run_tests.py there is a (somewhat crude) special case for MSVC on Windows which also seems to miss some optimization opportunities. Does it pass the tests if that is turned on?

If so, an option might be to add a --relaxed parameter that gets called from the cmake build system.

**Comment by bennybp** [comment]
Yes, that causes the last remaining test to pass. So that looks like a reasonable solution

**Comment by bennybp** [comment]
Actually they all fail now :) The --relaxed parameter is being taken as the name in run_tests.py (you always set the test name to be sys.argv[1]). A quick change on my end causes them all to pass, though

    -if len(sys.argv) == 3 and sys.argv[2] == '--relaxed':
    +if len(sys.argv) == 3 and sys.argv[1] == '--relaxed':
         relaxed = True
    +    name = sys.argv[2]
    +else:
    +    name = sys.argv[1]
 
    -name = sys.argv[1]

**Comment by wjakob** [comment]
Ok, I just came to the same conclusion after getting warning emails from the CI bot ;) -- should be fixed now.

**Comment by bennybp** [comment]
Everything's looking good on my end. So this should officially be closed now. Thanks!
