### PR TITLE
Fix Compile Error: str Naming

### PR DESCRIPTION
**Pull request by ax3l**
Rebase and re-tested against `master` as of 48548ea4a5735acfb86c67354d3ea6a728169740, follow-up to #63: This fixes a build error compiling with `nvcc/7.5` + `gcc/4.9.2` causing a
```
./include/pybind11/pybind11.h(952): here

./include/pybind11/pytypes.h: In member function ‘pybind11::str pybind11::handle::str() const’:
./include/pybind11/pytypes.h:269:8: error: expected primary-expression before ‘class’
     return pybind11::str(str, false);
        ^
./include/pybind11/pytypes.h:269:8: error: expected ‘;’ before ‘class’
./include/pybind11/pytypes.h:269:8: error: expected primary-expression before ‘class’
```

Build command against a minimal example
```bash
# gcc: 4.9.2
# cuda: 7.5
# python: 2.7.6, 2.7.10, 3.4.3

# remove some doubled options & warnings from
#   `python[3]-config --cflags --ldflags --libs`
nvcc -shared -std=c++11 --compiler-options -fPIC \
  -I ./include/ -I/opt/pkg/devel/python/3.4.3/include/python3.4m \
  -I/opt/pkg/devel/python/3.4.3/include/python3.4m -DNDEBUG -g \
  -L/opt/pkg/devel/python/3.4.3/lib \
  -lpython3.4m -lpthread -ldl  -lutil -lm \
  -Xlinker -export-dynamic -lpython3.4m -lpthread -ldl -lutil -lm \
  mandelbrot.cu -o mandelbrot.so
```

### CODE REVIEW

**Comment by ax3l** [comment]
oh absolutely. sorry for that :)

**Comment by ax3l** [comment]
If you are interested, I am currently working on [travis integration for CUDA 7.5](https://github.com/ax3l/pybind11/tree/topic-cudaTesting) testing for the project, creating bindings for a simple `main.cu`.

A ragged/hacked compile command would be easy but if you are interested we could try to get it into your CMake + examples tree, too.

**Comment by wjakob** [comment]
Dear Axel,

I’m really surprised that NVCC can compile something as complicated as pybind11 (i.e. using metatemplate programming, various features c++11 and c++14 etc.).
I assume then that it’s internally based on GCC or LLVM or something similar?

Thanks for offering to post travis integration. I would be up for it if it is only a small addition to the existing travis file (I don’t think it’s a good idea to add to the cmake build system since most users won’t be needing CUDA).

Cheers,
Wenzel

PS: Thanks for the PR!

**Comment by ax3l** [comment]
Dear Wenzel,

thanks a lot for the merge! Actually, I am happy as well to see how easy it worked. This is mostly due to your excellent code base (and it being header-only, avoiding the `__host__`/`__device__` C++ extensions) and the now mature C++11 support in CUDA 7.5.

Trivia: I also got a (patched) version of boost::python running last year with C++98 and CMake ([1/2 PRs accepted upstream](https://github.com/boostorg/python/issues?q=author%3Aax3l)). With nvcc: since more then 5 years we are using nvcc with *heavy* meta-programming in C++98 (and now C++11) for several [of our projects](https://github.com/ComputationalRadiationPhysics/picongpu). Also, most boost header-only libraries always worked with nvcc :) Internally, it's something [llvm based since a couple of years](http://blog.llvm.org/2011/12/nvidia-cuda-41-compiler-now-built-on.html), also nvidia released a [backend for llvm](https://developer.nvidia.com/CUDA-LLVM-Compiler) as open source and google (?) is working on a [fully free llvm CUDA implementation](http://llvm.org/docs/CompileCudaWithLLVM.html).

PR with CI and description will come soon, thank you! I think it's always quite cool to test against as much (recent) compilers as possible to spot the last little warnings and tweaks. Also, I am really looking forward to use pybind11 with cuda to make our scientific projects more scriptable and interactive :fireworks:

**Comment by ax3l** [comment]
@wjakob sorry to bother, but did you accidentally rebase this merge away?

The current state in `master` is still without the fix, even after this PR was merged:
  https://github.com/wjakob/pybind11/blob/61587164ed74fa1d452ec6ff747502a8aeba4c49/include/pybind11/pytypes.h#L263-L269

  https://travis-ci.org/ax3l/pybind11/jobs/103239619

Here is the 2nd follow up (we get to it :) ): #71

**Comment by wjakob** [comment]
I did, seems to have gotten lost in a rebase -- sorry, my bad.
